//! Generates `docs/porkchop.svg` for this crate's README — a real Earth-Mars
//! porkchop plot, solved cell by cell against the actual planetary ephemeris
//! rather than drawn by hand. Run with:
//!
//! ```sh
//! cargo run --example porkchop -p terramenta-charta
//! ```

use std::fmt::Write as _;

use terramenta_charta::{Contour, contours, porkchop_grid};
use terramenta_solare::lambert::TransferDirection;
use terramenta_solare::{Epoch, solar_system};

const WIDTH: f64 = 880.0;
const HEIGHT: f64 = 560.0;
const MARGIN_TOP: f64 = 34.0;
const MARGIN_RIGHT: f64 = 20.0;
const MARGIN_BOTTOM: f64 = 62.0;
const MARGIN_LEFT: f64 = 92.0;
const CONTOUR_COUNT: usize = 9;
const GRID_STEPS: usize = 70;
const DAY_SECONDS: f64 = 86_400.0;

fn main() {
    let tree = solar_system();
    let (sun, earth, mars) = (
        tree.find("Sun").unwrap(),
        tree.find("Earth").unwrap(),
        tree.find("Mars").unwrap(),
    );

    // A window either side of the near-optimal Earth-Mars transfer this
    // crate's own tests use, wide enough to show the full bowl of cheap
    // transfers and the dead zone where arrival falls before departure.
    let departure_start = Epoch::J2000.advanced_by_seconds(1_100.0 * DAY_SECONDS);
    let departure_end = Epoch::J2000.advanced_by_seconds(1_400.0 * DAY_SECONDS);
    let arrival_start = Epoch::J2000.advanced_by_seconds(1_300.0 * DAY_SECONDS);
    let arrival_end = Epoch::J2000.advanced_by_seconds(1_700.0 * DAY_SECONDS);

    let grid = porkchop_grid(
        &tree,
        sun,
        earth,
        mars,
        departure_start,
        departure_end,
        GRID_STEPS,
        arrival_start,
        arrival_end,
        GRID_STEPS,
        TransferDirection::Prograde,
    );

    let (cost_min, cost_max_actual) = grid
        .total_delta_v_bounds_km_s()
        .expect("a real Earth-Mars window should have solved cells");
    // A cell right along the arrival-before-departure boundary is asking for
    // an almost-instantaneous hop across half an AU, which Lambert answers
    // with an enormous but finite delta-v — into the thousands of km/s at
    // this grid's resolution. Scaling the colour field and the contours to
    // that true max would crush the whole interesting range into a sliver of
    // blue, so both are capped at a figure real chemical propulsion could
    // ever actually spend.
    let cost_max_display = cost_max_actual.min(cost_min + 20.0);
    let levels: Vec<f64> = (1..=CONTOUR_COUNT)
        .map(|index| {
            cost_min + (cost_max_display - cost_min) * index as f64 / (CONTOUR_COUNT as f64 + 1.0)
        })
        .collect();

    let xs: Vec<f64> = grid
        .departures
        .iter()
        .map(|e| e.to_unix_seconds())
        .collect();
    let ys: Vec<f64> = grid.arrivals.iter().map(|e| e.to_unix_seconds()).collect();
    let field = grid.total_delta_v_km_s();
    let contour_lines = contours(&xs, &ys, &field, &levels);

    let svg = render_svg(&xs, &ys, &field, &contour_lines, cost_min, cost_max_display);
    std::fs::create_dir_all("docs").expect("docs/ should be creatable");
    std::fs::write("docs/porkchop.svg", &svg).expect("docs/porkchop.svg should be writable");
    println!(
        "Wrote docs/porkchop.svg — total delta-v {cost_min:.2}-{cost_max_display:.2}+ km/s across the grid (true max {cost_max_actual:.0} km/s, off the chart)"
    );
}

fn render_svg(
    xs: &[f64],
    ys: &[f64],
    field: &[Option<f64>],
    contour_lines: &[Contour],
    cost_min: f64,
    cost_max: f64,
) -> String {
    let plot_width = WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
    let plot_height = HEIGHT - MARGIN_TOP - MARGIN_BOTTOM;
    let (x_min, x_max) = (xs[0], xs[xs.len() - 1]);
    let (y_min, y_max) = (ys[0], ys[ys.len() - 1]);

    let to_x = |seconds: f64| MARGIN_LEFT + (seconds - x_min) / (x_max - x_min) * plot_width;
    // Arrival increases upward, the way a porkchop plot is conventionally drawn.
    let to_y =
        |seconds: f64| MARGIN_TOP + plot_height - (seconds - y_min) / (y_max - y_min) * plot_height;

    let cell_width = plot_width / xs.len() as f64;
    let cell_height = plot_height / ys.len() as f64;

    let mut svg = String::new();
    let _ = writeln!(
        svg,
        "<!--\n  Terramenta - a porkchop plot: total transfer delta-v over departure date\n  \
         against arrival date, Earth to Mars, solved cell by cell by this crate's\n  \
         own Lambert-transfer grid against the real planetary ephemeris.\n\n  Generated by \
         the `porkchop` example in this crate (see its own README); do not edit by hand.\n-->"
    );
    let _ = writeln!(
        svg,
        r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="{WIDTH}" height="{HEIGHT}" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace">"#
    );
    let _ = writeln!(
        svg,
        r##"<rect width="{WIDTH}" height="{HEIGHT}" fill="#06121f"/>"##
    );

    for (departure_index, &departure_seconds) in xs.iter().enumerate() {
        for (arrival_index, &arrival_seconds) in ys.iter().enumerate() {
            let Some(value) = field[departure_index * ys.len() + arrival_index] else {
                continue;
            };
            let fraction = if cost_max > cost_min {
                ((value - cost_min) / (cost_max - cost_min)).min(1.0)
            } else {
                0.0
            };
            let hue = 220.0 - 220.0 * fraction;
            let x = to_x(departure_seconds) - cell_width / 2.0;
            let y = to_y(arrival_seconds) - cell_height / 2.0;
            let _ = writeln!(
                svg,
                r#"<rect x="{x:.2}" y="{y:.2}" width="{cell_width:.2}" height="{cell_height:.2}" fill="hsl({hue:.1}deg 75% 45%)"/>"#
            );
        }
    }

    for contour in contour_lines {
        if contour.segments.is_empty() {
            continue;
        }
        let mut path = String::new();
        for (a, b) in &contour.segments {
            let _ = write!(
                path,
                "M{:.2},{:.2} L{:.2},{:.2} ",
                to_x(a.0),
                to_y(a.1),
                to_x(b.0),
                to_y(b.1)
            );
        }
        let _ = writeln!(
            svg,
            r#"<path d="{path}" fill="none" stroke="rgba(6,10,18,0.65)" stroke-width="0.7"/>"#
        );
    }

    for &index in &tick_indices(xs.len()) {
        let x = to_x(xs[index]);
        let label_y = HEIGHT - MARGIN_BOTTOM + 18.0;
        let _ = writeln!(
            svg,
            r#"<line x1="{x:.2}" y1="{MARGIN_TOP:.2}" x2="{x:.2}" y2="{:.2}" stroke="rgba(207,224,255,0.16)" stroke-width="0.6"/>"#,
            HEIGHT - MARGIN_BOTTOM
        );
        let _ = writeln!(
            svg,
            r#"<text x="{x:.2}" y="{label_y:.2}" fill="rgba(207,224,255,0.55)" font-size="12" text-anchor="middle" transform="rotate(-30 {x:.2} {label_y:.2})">{}</text>"#,
            iso_date(xs[index])
        );
    }
    for &index in &tick_indices(ys.len()) {
        let y = to_y(ys[index]);
        let _ = writeln!(
            svg,
            r#"<line x1="{MARGIN_LEFT:.2}" y1="{y:.2}" x2="{:.2}" y2="{y:.2}" stroke="rgba(207,224,255,0.16)" stroke-width="0.6"/>"#,
            WIDTH - MARGIN_RIGHT
        );
        let _ = writeln!(
            svg,
            r#"<text x="{:.2}" y="{:.2}" fill="rgba(207,224,255,0.55)" font-size="12" text-anchor="end">{}</text>"#,
            MARGIN_LEFT - 8.0,
            y + 4.0,
            iso_date(ys[index])
        );
    }

    let _ = writeln!(
        svg,
        r#"<rect x="{MARGIN_LEFT:.2}" y="{MARGIN_TOP:.2}" width="{plot_width:.2}" height="{plot_height:.2}" fill="none" stroke="rgba(207,224,255,0.3)"/>"#
    );
    let _ = writeln!(
        svg,
        r##"<text x="{:.2}" y="{:.2}" fill="#cfe0ff" font-size="13" text-anchor="middle">Departure date</text>"##,
        MARGIN_LEFT + plot_width / 2.0,
        HEIGHT - 8.0
    );
    let arrival_label_y = MARGIN_TOP + plot_height / 2.0;
    let _ = writeln!(
        svg,
        r##"<text x="16" y="{arrival_label_y:.2}" fill="#cfe0ff" font-size="13" text-anchor="middle" transform="rotate(-90 16 {arrival_label_y:.2})">Arrival date</text>"##
    );
    let _ = writeln!(
        svg,
        r##"<text x="{MARGIN_LEFT:.2}" y="20" fill="#cfe0ff" font-size="13">Earth → Mars total Δv, capped at {cost_max:.0} km/s (blue {cost_min:.1}, red {cost_max:.0}+)</text>"##
    );

    let _ = writeln!(svg, "</svg>");
    svg
}

/// Up to 6 indices spanning `0..length`, including both ends.
fn tick_indices(length: usize) -> Vec<usize> {
    let count = 6.min(length);
    if length <= count {
        return (0..length).collect();
    }
    (0..count)
        .map(|i| (i * (length - 1)) / (count - 1))
        .collect()
}

fn iso_date(unix_seconds: f64) -> String {
    let (year, month, day) = civil_from_days((unix_seconds / DAY_SECONDS).floor() as i64);
    format!("{year:04}-{month:02}-{day:02}")
}

/// Days since the Unix epoch to a proleptic Gregorian date — Howard
/// Hinnant's `civil_from_days` algorithm, chosen over a date-handling
/// dependency for the one thing this docs-generating example needs once:
/// axis labels.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = (z - era * 146_097) as u64;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let year = year_of_era as i64 + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = (day_of_year - (153 * month_prime + 2) / 5 + 1) as u32;
    let month = if month_prime < 10 {
        month_prime + 3
    } else {
        month_prime - 9
    } as u32;
    (if month <= 2 { year + 1 } else { year }, month, day)
}
